export const factoryAbi = [
  {
    type: "function",
    name: "createToken",
    inputs: [
      {
        name: "config",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "initialSupply", type: "uint256" },
          { name: "featureFlags", type: "uint256" },
          { name: "maxWalletAmount", type: "uint256" },
          { name: "maxTxAmount", type: "uint256" },
          { name: "buyTaxBps", type: "uint16" },
          { name: "sellTaxBps", type: "uint16" },
          {
            name: "taxDistribution",
            type: "tuple",
            components: [
              { name: "marketingWallet", type: "address" },
              { name: "developmentWallet", type: "address" },
              { name: "treasuryWallet", type: "address" },
              { name: "communityWallet", type: "address" },
              { name: "operationsWallet", type: "address" },
              { name: "liquidityWallet", type: "address" },
              { name: "marketingBps", type: "uint16" },
              { name: "developmentBps", type: "uint16" },
              { name: "treasuryBps", type: "uint16" },
              { name: "communityBps", type: "uint16" },
              { name: "operationsBps", type: "uint16" },
              { name: "liquidityBps", type: "uint16" },
            ],
          },
          {
            name: "antiBot",
            type: "tuple",
            components: [
              { name: "launchGuardEnabled", type: "bool" },
              { name: "maxLaunchBuy", type: "uint256" },
              { name: "maxLaunchWallet", type: "uint256" },
              { name: "protectionDuration", type: "uint256" },
            ],
          },
          { name: "owner", type: "address" },
        ],
      },
    ],
    outputs: [{ name: "token", type: "address" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "calculateCreationFee",
    inputs: [{ name: "featureFlags", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseCreationFee",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creationFee",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pauseFactory",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpauseFactory",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCreationFee",
    inputs: [{ name: "fee", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeRecipient",
    inputs: [{ name: "recipient", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tokenCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allTokens",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenCreator",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isIOPnToken",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "TokenCreated",
    inputs: [
      { name: "token", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "symbol", type: "string", indexed: false },
      { name: "featureFlags", type: "uint256", indexed: false },
      { name: "initialSupply", type: "uint256", indexed: false },
    ],
  },
] as const;

export const tokenAbi = [
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "enableTrading",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "featureFlags",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tradingEnabled",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isOwnershipRenounced",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "TAX_DISTRIBUTION",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "marketingWallet", type: "address" },
          { name: "developmentWallet", type: "address" },
          { name: "treasuryWallet", type: "address" },
          { name: "communityWallet", type: "address" },
          { name: "operationsWallet", type: "address" },
          { name: "liquidityWallet", type: "address" },
          { name: "marketingBps", type: "uint16" },
          { name: "developmentBps", type: "uint16" },
          { name: "treasuryBps", type: "uint16" },
          { name: "communityBps", type: "uint16" },
          { name: "operationsBps", type: "uint16" },
          { name: "liquidityBps", type: "uint16" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setTaxWallet",
    inputs: [
      { name: "slot", type: "uint8" },
      { name: "wallet", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
] as const;

export const liquidityRouterAbi = [
  {
    type: "function",
    name: "addLiquidityViaPrimary",
    inputs: [
      { name: "token", type: "address" },
      { name: "tokenAmount", type: "uint256" },
      { name: "tokenMin", type: "uint256" },
      { name: "ethMin", type: "uint256" },
    ],
    outputs: [{ name: "liquidity", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "addLiquidityViaUniswap",
    inputs: [
      { name: "token", type: "address" },
      { name: "tokenAmount", type: "uint256" },
      { name: "tokenMin", type: "uint256" },
      { name: "ethMin", type: "uint256" },
    ],
    outputs: [{ name: "liquidity", type: "uint256" }],
    stateMutability: "payable",
  },
] as const;
