[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "corepack prepare pnpm@9.15.0 --activate",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm --filter @iopn/api build"]

[start]
cmd = "pnpm db:push && pnpm --filter @iopn/api start"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "corepack prepare pnpm@9.15.0 --activate",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter @iopn/database generate",
  "pnpm --filter @iopn/api build"
]

[start]
cmd = "pnpm db:push && pnpm --filter @iopn/api start"
