[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "pnpm db:push && pnpm --filter @iopn/api start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
